Codigo/Alugai/AlugaiWEB/Controllers/AluguelController.cs
using AlugaiWEB.Models;
using AutoMapper;
using Core;
using Core.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace AlugaiWEB.Controllers
{
    public class AluguelController : Controller
    {
        IAluguelService _aluguelService;
        IStatuspagamentoService _statusPagamentoService;
        IMapper _mapper;

        public AluguelController(IAluguelService aluguelService,
                                 IStatuspagamentoService statuspagamentoService, IMapper mapper)
        {
            _aluguelService = aluguelService;
            _statusPagamentoService = statuspagamentoService;
            _mapper = mapper;
        }

        public ActionResult Index()
        {
            var listarAlugueis = _aluguelService.ObterTodos();
            var listarAlugueisModel = _mapper.Map<List<AluguelModel>>(listarAlugueis);

            return View(listarAlugueisModel);
        }

        public ActionResult Details(int id)
        {
            Aluguel aluguel = _aluguelService.Buscar(id);
            AluguelModel aluguelModel = _mapper.Map<AluguelModel>(aluguel);

            return View(aluguelModel);
        }

        public ActionResult Create()
        {
            IEnumerable<Statuspagamento> listarStatusPagamento = _statusPagamentoService.ObterTodos();

            ViewBag.IdStatusPagamento = new SelectList(listarStatusPagamento, "CodigoStatusPagamento", "Descricao", null);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AluguelModel aluguelModel)
        {
            if (ModelState.IsValid)
            {
                var aluguel = _mapper.Map<Aluguel>(aluguelModel);
                _aluguelService.Inserir(aluguel);
            }
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Edit(int id)
        {
            Aluguel aluguel= _aluguelService.Buscar(id);
            AluguelModel aluguelModel = _mapper.Map<AluguelModel>(aluguel);

            IEnumerable<Statuspagamento> listarStatusPagamento = _statusPagamentoService.ObterTodos();
            ViewBag.IdStatusPagamento = new SelectList(listarStatusPagamento, "CodigoStatusPagamento", "Descricao", null);

            return View(aluguelModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, AluguelModel aluguelModel)
        {
            if (ModelState.IsValid)
            {
                var aluguel = _mapper.Map<Aluguel>(aluguelModel);
                _aluguelService.Alterar(aluguel);
            }
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Delete(int id)
        {
            Aluguel aluguel = _aluguelService.Buscar(id);
            AluguelModel aluguelModel = _mapper.Map<AluguelModel>(aluguel);
            return View(aluguelModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, AluguelModel aluguelModel)
        {
            _aluguelService.Excluir(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Codigo/Alugai/AlugaiWEB/Controllers/AnuncioController.cs
using AlugaiWEB.Models;
using AutoMapper;
using Core;
using Core.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;

namespace AlugaiWEB.Controllers
{
    public class AnuncioController : Controller
    {
        IAnuncioService _anuncioService;
        IImovelService _imovelService;
        IPessoaService _pessoaService;
        IMapper _mapper;

        public AnuncioController(IAnuncioService anuncioService, IImovelService imovelService,
                                 IPessoaService pessoaService, IMapper mapper)
        {
            _anuncioService = anuncioService;
            _imovelService = imovelService;
            _pessoaService = pessoaService;
            _mapper = mapper;
        }

        public ActionResult Index()
        {
            var listarAnuncios = _anuncioService.ObterTodos();
            var listarAnunciosModel = _mapper.Map<List<AnuncioModel>>(listarAnuncios);

            return View(listarAnunciosModel);
        }

        public ActionResult Details(int id)
        {
            Anuncio anuncio = _anuncioService.Buscar(id);
            AnuncioModel anuncioModel = _mapper.Map<AnuncioModel>(anuncio);

            return View(anuncioModel);
        }

        public ActionResult Create()
        {
            IEnumerable<Imovel> listarImoveis = _imovelService.ObterTodos();
            IEnumerable<Pessoa> listarPessoas = _pessoaService.ObterTodos();

            ViewBag.IdImovel = new SelectList(listarImoveis, "CodigoImovel", "Descricao", null);
            ViewBag.IdPessoa = new SelectList(listarPessoas, "CodigoPessoa", "Nome", null);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AnuncioModel anuncioModel)
        {
            if (ModelState.IsValid)
            {
                var anuncio = _mapper.Map<Anuncio>(anuncioModel);

                anuncio.Data = DateTime.Now;

                _anuncioService.Inserir(anuncio);
            }
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Edit(int id)
        {
            Anuncio anuncio = _anuncioService.Buscar(id);
            AnuncioModel anuncioModel = _mapper.Map<AnuncioModel>(anuncio);

            IEnumerable<Imovel> listarImoveis = _imovelService.ObterTodos();
            IEnumerable<Pessoa> listarPessoas = _pessoaService.ObterTodos();

            ViewBag.IdImovel = new SelectList(listarImoveis, "CodigoImovel", "Descricao", null);
            ViewBag.IdPessoa = new SelectList(listarPessoas, "CodigoPessoa", "Nome", null);

            return View(anuncioModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, AnuncioModel anuncioModel)
        {
            if (ModelState.IsValid)
            {
                var anuncio = _mapper.Map<Anuncio>(anuncioModel);
                _anuncioService.Alterar(anuncio);
            }
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Delete(int id)
        {
            Anuncio anuncio = _anuncioService.Buscar(id);
            AnuncioModel anuncioModel = _mapper.Map<AnuncioModel>(anuncio);
            return View(anuncioModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, AnuncioModel anuncioModel)
        {
            _anuncioService.Excluir(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Codigo/Alugai/AlugaiWEB/Controllers/ImovelController.cs
using AutoMapper;
using Core.Services;
using Core;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using AlugaiWEB.Models;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AlugaiWEB.Controllers
{
    public class ImovelController : Controller
    {
        IImovelService _imovelService;
        IMapper _mapper;
        public ImovelController(IImovelService imovelService, IMapper mapper)
        {
            _imovelService = imovelService;
            _mapper = mapper;
        }

        public ActionResult Index()
        {
            var listarImoveis = _imovelService.ObterTodos();
            var listarImoveisModel = _mapper.Map<List<ImovelModel>>(listarImoveis);

            return View(listarImoveisModel);
        }

        public ActionResult Details(int id)
        {
            Imovel imovel = _imovelService.Buscar(id);
            ImovelModel imovelModel = _mapper.Map<ImovelModel>(imovel);

            return View(imovelModel);
        }


        public ActionResult Create()
        {

            var tiposImoveis = new[]
            {
                new SelectListItem { Value = "Apartamento", Text = "Apartamento" },
                new SelectListItem { Value = "Casa", Text = "Casa" },
                new SelectListItem { Value = "Casa de condominio", Text = "Casa de Condominio" },
                new SelectListItem { Value = "Garagem", Text = "Garagem" },
                new SelectListItem { Value = "Galpão/Depósito", Text = "Galpão/Depósito" },
                new SelectListItem { Value = "Terreno/Lote", Text = "Terreno/Lote" },
                new SelectListItem { Value = "Loja/Salão", Text = "Loja/Salão" },
            };

            ViewBag.TiposImoveis = new SelectList(tiposImoveis, "Value", "Text");
            
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ImovelModel imovelModel)
        {
            if(ModelState.IsValid)
            {
                var imovel = _mapper.Map<Imovel>(imovelModel);
                _imovelService.Inserir(imovel);
            }
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Edit(int id)
        {
            Imovel imovel = _imovelService.Buscar(id);
            ImovelModel imovelModel = _mapper.Map<ImovelModel>(imovel);
            return View(imovelModel);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ImovelModel imovelModel)
        {
            if (ModelState.IsValid)
            {
                var imovel = _mapper.Map<Imovel>(imovelModel);
                _imovelService.Alterar(imovel);
            }
            return RedirectToAction(nameof(Index));
        }

        
        public ActionResult Delete(int id)
        {
            Imovel imovel = _imovelService.Buscar(id);
            ImovelModel imovelModel = _mapper.Map<ImovelModel>(imovel);
            return View(imovelModel);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, ImovelModel imovelModel)
        {
            _imovelService.Excluir(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Codigo/Alugai/AlugaiWEB/Controllers/PessoaController.cs
using AlugaiWEB.Models;
using AutoMapper;
using Core;
using Core.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace AlugaiWEB.Controllers
{
    public class PessoaController : Controller
    {

       
        IPessoaService _pessoaService;
        IMapper _mapper;

        public PessoaController(IPessoaService pessoaService, IMapper mapper)
        {
            _pessoaService = pessoaService;
            _mapper = mapper;
        }
        // GET: PessoaController
        public ActionResult Index()
        {
            IEnumerable<Pessoa> listarPessoas = _pessoaService.ObterTodos();
             var listarPessoasModel = _mapper.Map<List<PessoaModel>>(listarPessoas);
           
            return View(listarPessoasModel);
        }

        // GET: PessoaController/Details/5
        public ActionResult Details(int id)
        {
            Pessoa pessoa = _pessoaService.Buscar(id);
            PessoaModel pessoaModel = _mapper.Map<PessoaModel>(pessoa);
            return View(pessoaModel);
        }

        // GET: PessoaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PessoaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PessoaModel pessoaModel)
        {
           if(ModelState.IsValid)
            {
                var pessoa = _mapper.Map<Pessoa>(pessoaModel);
                _pessoaService.Inserir(pessoa);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: PessoaController/Edit/5
        public ActionResult Edit(int id)
        {
            Pessoa pessoa = _pessoaService.Buscar(id);
            PessoaModel pessoaModel = _mapper.Map<PessoaModel>(pessoa);
            return View(pessoaModel);
        }

        // POST: PessoaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PessoaModel pessoaModel)
        {
            if (ModelState.IsValid)
            {
                var pessoa = _mapper.Map<Pessoa>(pessoaModel);
                _pessoaService.Alterar(pessoa);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: PessoaController/Delete/5
        public ActionResult Delete(int id)
        {
            Pessoa pessoa = _pessoaService.Buscar(id);
            PessoaModel pessoaModel = _mapper.Map<PessoaModel>(pessoa);
            return View(pessoaModel);
        }

        // POST: PessoaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, PessoaModel pessoaModel)
        {
            _pessoaService.Excluir(id);
            return RedirectToAction(nameof(Index));

        }
    }
}

Codigo/Alugai/AlugaiWEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/footer-with-button-logo.css">

    <!-- Smartlook - Usability Test -->
    <script type='text/javascript'>
        window.smartlook || (function (d) {
            var o = smartlook = function () { o.api.push(arguments) }, h = d.getElementsByTagName('head')[0];
            var c = d.createElement('script'); o.api = new Array(); c.async = true; c.type = 'text/javascript';
            c.charset = 'utf-8'; c.src = 'https://rec.smartlook.com/recorder.js'; h.appendChild(c);
        })(document);
        smartlook('init', '6b973b8a8a1e447616ee7bd3c89e3d580e8c0f40');
    </script>


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-light">
            <!--Logo-->
            <a href="/" class="navbar-brand">
                <img src="~/imagens/logo.png" class="img-fluid" width="150">
            </a>

            <!--Menu Hamburguer-->
            <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-navegacao">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse navegacao" id="nav-navegacao">
                <!--Inicio Barra de navegação-->
                <partial name="_LoginPartial" />
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a href="" class="nav-link">Anunciar</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="IndexMeusDados">
                            <i class="far fa-user mr-1"></i>Entrar ou Cadastrar
                        </a>
                    </li>
                </ul>
            </div> <!--Fim Barra de navegação-->
        </nav>
    </header>

    @Html.Partial("_filtersHeader")


    <div class="container-home">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!--Inicio do Rodapé-->
    <div class="content">
    </div>
    <footer id="myFooter">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <a href="/" class="navbar-brand">
                        <img src="~/imagens/logo_write.png" class="img-fluid" width="150">
                    </a>
                </div>
                <div class="col-sm-2">
                    <h5>Inicio</h5>
                    <ul>
                        <li>Home</li>
                        <li>Trabalhe Conosco</li>
                        <li>Politica de Privacidade</li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <h5>Sobre-nós</h5>
                    <ul>
                        <li>Informações da Empresa</li>
                        <li>Contato</li>
                        <li>Blog</li>
                    </ul>
                </div>
                <div class="col-sm-2">
                    <h5>Suporte</h5>
                    <ul>
                        <li>FAQ</li>
                        <li>Telefones</li>
                        <li>Chat</li>
                    </ul>
                </div>
                <div class="col-sm-3">
                    <button type="button" class="bt btn-default">Anunciar</button>
                    <button type="button" class="btn btn-default">Contato</button>
                    </a>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <p>© 2021 Copyright - Alugai</p>
        </div>
    </footer>
    <!--Fim do Rodapé-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Codigo/Alugai/AlugaiWEB/Views/Shared/_MeusDados.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap5/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/style.css" />

    <!-- Smartlook - Usability Test -->
    <script type='text/javascript'>
        window.smartlook || (function (d) {
            var o = smartlook = function () { o.api.push(arguments) }, h = d.getElementsByTagName('head')[0];
            var c = d.createElement('script'); o.api = new Array(); c.async = true; c.type = 'text/javascript';
            c.charset = 'utf-8'; c.src = 'https://rec.smartlook.com/recorder.js'; h.appendChild(c);
        })(document);
        smartlook('init', '6b973b8a8a1e447616ee7bd3c89e3d580e8c0f40');
    </script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-light">

            <div class="container-fluid">
                <a href="/" class="navbar-brand">
                    <img src="~/imagens/logo.png" class="img-fluid" width="150">
                </a>

                <!--Menu Hamburguer-->
                <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-navegacao">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="d-flex justify-content-end" id="nav-navegacao">
                    <!--Inicio Barra de navegação-->
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a asp-controller="Anuncio" asp-action="Index" class="nav-link">Anunciar</a>
                        </li>

                        <li>
                            <div class="dropdown logoff" style="margin: auto 0;">
                                <a class="nav-link dropdown-toggle" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <img class="user-img" src="../imagens/user.png">
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" href="/">Sair</a>
                                </div>
                            </div>
                        </li>

                    </ul>
                </div> <!--Fim Barra de navegação-->

            </div>
            <!--Logo-->

        </nav>
    </header>

    <div class="d-flex" id="wrapper" style="padding:0;">

        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">Alugaí</div>
            <div class="list-group list-group-flush">

                <a class="list-group-item list-group-item-action bg-light" asp-controller="Pessoa" asp-action="Index">Minha Conta</a>
                <a class="list-group-item list-group-item-action bg-light" asp-controller="Imovel" asp-action="Index">Resumo</a>
                <a class="list-group-item list-group-item-action bg-light" asp-controller="Pessoa" asp-action="Index">Meus Dados</a>
                <a class="list-group-item list-group-item-action bg-light" asp-controller="Imovel" asp-action="Index">Meus Imoveis</a>
                <a class="list-group-item list-group-item-action bg-light" asp-controller="Aluguel" asp-action="Index">Meus Alugueis</a>

            </div>
        </div>

        <div id="page-content-wrapper">
            <button class="btn btn-primary mt-2 ml-2" id="menu-toggle">
                <i class="fas fa-bars"></i>
            </button>

            <div class="p-3">
                @RenderBody()

            </div>
        </div>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AlugaiWEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.inputmask.js"></script>
    <script src="~/lib/bootstrap5/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/cep.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

<script>
    $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
</script>

Codigo/Alugai/AlugaiWEB/Views/Shared/_filtersHeader.cshtml
<!-- Início header -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

<div class="filters-header">
    <div class="bg"></div>
    <div class="gradient"></div>
    <div class="inner">
        <div class="container">
            <div class="row">
                <div class="d-flex justify-content-center mt-5">
                    <div class="filters-content">
                        <h1 class="display-3 text-uppercase">Encontre as melhores casas</h1>
                        <h1 class="display-3 text-uppercase">Pelos melhores preços</h1>
                        <button type="button" class="btn btn-primary dropdown-toggle mt-3" data-bs-toggle="modal" data-bs-target="#modalBuscarImovel">
                            Opções de Busca
                        </button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>


<!-- Button trigger modal -->
<!-- Modal -->
<div class="modal fade" id="modalBuscarImovel" tabindex="-1" aria-labelledby="modalBuscaImovelLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalBuscaImovelLabel">Buscar Imóvel</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <form>
                    <div class="row">

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="tipoImovel">Tipo do Imóvel</label>
                                <select class="form-select" id="tipoImovel">
                                    <option>CASA</option>
                                    <option>APARTAMENTO</option>
                                    <option>SALÃO DE FESTAS</option>
                                </select>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="formGroupExampleInput">Localização do Imóvel</label>
                                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Rua, Bairro, Cidade, CEP">
                            </div>
                        </div>

                    </div>

                    <div class="row">

                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="faixaPreco">Faixa de Preço</label>
                                <select class="form-select" id="faixaPreco">
                                    <option>R$300,00</option>
                                    <option>R$400,00</option>
                                    <option>R$500,00</option>
                                </select>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="qtdQuartos">Quartos</label>
                                <select class="form-select" id="qtdQuartos">
                                    <option>1</option>
                                    <option>2</option>
                                    <option>3+</option>
                                </select>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="qtdBanheiros">Banheiros</label>
                                <select class="form-select" id="qtdBanheiros">
                                    <option>1</option>
                                    <option>2</option>
                                    <option>3+</option>
                                </select>
                            </div>
                        </div>

                    </div>

                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Sair</button>
                <button type="button" class="btn btn-primary">Buscar</button>
            </div>
        </div>
    </div>
</div>

<!-- Fim header -->